spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    generate-ddl: off
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: SA
    password: ''

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret_key: ${jwt_secret_key}

api-keys:
  football: ${football-api-key}
  basketball: ${basketball-api-key}
  baseball: ${baseball-api-key}

cloud:
  aws:
    credentials:
      accessKey: ${aws_accessKey}
      secretKey: ${aws_secretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: sports-echo

oauth:
  api:
    secret:
      naver: ${naver-api-secret}
      google: ${google-api-secret}
    key:
      kakao: ${kakao-api-key}
      naver: ${naver-api-key}
      google: ${google-api-key}

admin:
  key:
    secret: ${admin-secret-key}