name: 'sports_echo_ci'
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "dev1" ]
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BASEBALL_API_KEY: ${{ secrets.BASEBALL_API_KEY }}
      BASKETBALL_API_KEY: ${{ secrets.BASKETBALL_API_KEY }}
      FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_API_SECRET: ${{ secrets.GOOGLE_API_SECRET }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
      NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
      NAVER_API_SECRET: ${{ secrets.NAVER_API_SECRET }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4


      - name: Java Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Upload Jacoco Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html