name: 'sports_echo_ci'
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "dev1" ]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      admin-secret-key: ${{ secrets.ADMIN_SECRET_KEY }}
      aws_accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      aws_secretKey: ${{ secrets.AWS_SECRET_KEY }}
      baseball-api-key: ${{ secrets.BASEBALL_API_KEY }}
      basketball-api-key: ${{ secrets.BASKETBALL_API_KEY }}
      football-api-key: ${{ secrets.FOOTBALL_API_KEY }}
      google-api-key: ${{ secrets.GOOGLE_API_KEY }}
      google-api-secret: ${{ secrets.GOOGLE_API_SECRET }}
      your_username: ${{ secrets.YOUR_USERNAME }}
      your_password: ${{ secrets.YOUR_PASSWORD }}
      jwt.secret_key: ${{ secrets.JWT_SECRET_KEY }}
      kakao-api-key: ${{ secrets.KAKAO_API_KEY }}
      naver-api-key: ${{ secrets.NAVER_API_KEY }}
      naver-api-secret: ${{ secrets.NAVER_API_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Run chmod to make gralew executable
        run: chmod +x ./gradlew

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Restore dependencies
        run: ./gradlew dependencies

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Build with Gradle
        env:
          SPRING_PROFILES_ACTIVE: test
        run: |
          ./gradlew build -x test

      - name: Test with Gradle
        run: |
          ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Cleanup Gradle Cache
        if: ${{ always() }}
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties