name: 'sports_echo_ci'
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "dev1" ]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run chmod to make gralew executable
        run: chmod +x ./gradlew

      - name: Create appliction-test.properties
        run: |
          touch ./src/main/resources/application-ci.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-ci.yml
          cat ./src/main/resources/application-ci.yml

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Restore dependencies
        run: ./gradlew dependencies

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Build with Gradle
        run: |
          ./gradlew build -x test

      - name: Test with Gradle
        run: |
          ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: Cleanup Gradle Cache
        if: ${{ always() }}
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties